run: ## make the file executive and run in INFO mode
	chmod +x src/code.py 
	./src/code.py

debug: ## make the file executive and run in DEBUG mode
	chmod +x src/code.py
	./src/code.py --debug

help: ## print some help
	@ echo "run : Run in default mode (INFO)"
	@ echo "debug : Run in DEBUG mode"

